version: '2'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: testpasswd

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
