version: '2'

services:
  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - backend
    volumes:
      - staticfiles:/usr/app/static
  backend:
    build: .
    command: gunicorn rootapp.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - staticfiles:/usr/app/static
  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: testpasswd
      POSTGRES_DB: books

volumes:
  postgres_data:
  staticfiles: